//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Input/UserInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UserInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UserInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UserInputActions"",
    ""maps"": [
        {
            ""name"": ""Train"",
            ""id"": ""c3401460-d25e-4945-9b25-c5ab1063a864"",
            ""actions"": [
                {
                    ""name"": ""Pressure Absolute"",
                    ""type"": ""Value"",
                    ""id"": ""f1e35f4c-0ce3-4673-ad80-9c1ed6bffac4"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""AxisDeadzone(min=1.401298E-45,max=0.975)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pressure Modifier"",
                    ""type"": ""Value"",
                    ""id"": ""9f92cb2a-f4f3-486b-a49c-e5ed4ac0e959"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""ScaleVector2,StickDeadzone(min=0.125,max=0.925),AxisDeadzone(min=0.1,max=0.95)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Acceleration Absolute"",
                    ""type"": ""Value"",
                    ""id"": ""5b6dbf3d-5ad8-42f0-a77d-20dc2a868eff"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""AxisDeadzone(min=1.401298E-45,max=0.975)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Acceleration Modifier"",
                    ""type"": ""Value"",
                    ""id"": ""cec50a4c-5b71-4f18-83b3-fe85f5c301b8"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""ScaleVector2,StickDeadzone(min=0.125,max=0.925),AxisDeadzone(min=0.1,max=0.95)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Focus Panel"",
                    ""type"": ""Button"",
                    ""id"": ""ff850ff0-fb46-475a-b4f7-05dae7499649"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Exit Train"",
                    ""type"": ""Button"",
                    ""id"": ""bb043533-c691-4005-bfae-1d0f691651fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rebind Menu"",
                    ""type"": ""Button"",
                    ""id"": ""3e846cf3-7c9d-4777-9667-a2cd9527d067"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""3b7642e0-3a19-47f3-94f7-97038a278c88"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Change Perspective"",
                    ""type"": ""Button"",
                    ""id"": ""737fe307-3981-4f6a-a1b6-ff1aeccae8be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Saitek Left"",
                    ""type"": ""Value"",
                    ""id"": ""48c3fb3f-d142-4d10-90f3-3d4511eae76c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Saitek Right"",
                    ""type"": ""Value"",
                    ""id"": ""5dd4c33b-a2f4-4924-abc5-cbc8633ae527"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5d536afa-47e0-45ce-baf1-399873dc435b"",
                    ""path"": ""<Gamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0,y=0),StickDeadzone(min=0.125,max=0.95)"",
                    ""groups"": """",
                    ""action"": ""Acceleration Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89b4835a-9b22-4895-8889-82a330183a43"",
                    ""path"": ""<DualShockGamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0,y=0),StickDeadzone(min=0.125,max=0.95)"",
                    ""groups"": """",
                    ""action"": ""Acceleration Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""3c71413e-9a4c-4104-b646-524cde5637e2"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0.5)"",
                    ""groups"": """",
                    ""action"": ""Acceleration Modifier"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""7495b12a-8cfe-41f9-a7ca-36c269d2353c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125,max=0.95)"",
                    ""groups"": """",
                    ""action"": ""Acceleration Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9c342a09-ee82-402f-932b-5c0024be05fb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""39497b13-f942-410f-b46b-3a614be55f63"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Focus Panel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50a661b9-8ce0-4461-aff0-568ba5422c7d"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Focus Panel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc1d5b3c-0bb3-4a89-a8f8-8efc811eeed2"",
                    ""path"": ""<Gamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.125,max=0.95)"",
                    ""groups"": """",
                    ""action"": ""Pressure Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1656b6f-d5cc-4233-9812-8fdf92a08a92"",
                    ""path"": ""<DualShockGamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.125,max=0.95)"",
                    ""groups"": """",
                    ""action"": ""Pressure Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""c2c5c978-aa7d-4bd8-842f-ebe657d17151"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0.5)"",
                    ""groups"": """",
                    ""action"": ""Pressure Modifier"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""920a1a07-a841-4f88-8b64-76c960c86066"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125,max=0.95)"",
                    ""groups"": """",
                    ""action"": ""Pressure Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0b6e660d-6fda-4749-bcf0-5642ed960ad8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125,max=0.95)"",
                    ""groups"": """",
                    ""action"": ""Pressure Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""668afab4-2866-484d-96e8-cadf4de41b19"",
                    ""path"": ""<HID::Mega World USB Game Controllers>/rz"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration Absolute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45c1ce24-6715-418c-87b3-0e3c29a42350"",
                    ""path"": ""<HID::Mega World USB Game Controllers>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pressure Absolute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7dbb4dfd-9754-4d61-8224-b427c8dd293e"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit Train"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82e4c611-185a-4c48-926b-7424c461cec6"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit Train"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ce6bca0-737c-4941-8ecd-d0dc89e4c17a"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rebind Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f198f1e-20e8-4a85-b963-5366d7fef78e"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rebind Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08657547-aebf-486f-ad51-0a123db2858a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95bfcc0e-5a7c-4d0e-9d91-81b2696813cb"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ccb1dcb-bb34-4f86-a2cd-edd4fd96d8ca"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Perspective"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06374f26-61a0-449f-8082-1d221b1c0649"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Perspective"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c9073d5-1e25-46f4-a128-1f05a8e44f97"",
                    ""path"": ""<Joystick>{RightHand}/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Saitek Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6309db0f-7b6a-4676-b0a1-05da3548775e"",
                    ""path"": ""<Joystick>{LeftHand}/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Saitek Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player"",
            ""id"": ""a9e6506c-c1bf-4d85-8a8f-22ba5905ce03"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""eb44c0d4-c50b-4b43-9905-c73d6ebd4b65"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Camera"",
                    ""type"": ""Value"",
                    ""id"": ""3aaa53cd-9b20-4b81-bc04-100b49279eeb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Enter Train"",
                    ""type"": ""Button"",
                    ""id"": ""50f8ca63-336a-419d-9494-85c9aa2d1c67"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rebind Menu"",
                    ""type"": ""Button"",
                    ""id"": ""595df85c-f242-4939-9e96-33aa2d951084"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""d57fdddf-45df-4af9-9109-be8cca64b5ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1485c671-220e-4490-85dd-03612a1bc036"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d8a84d37-1e87-43af-bdb1-069d7ab98728"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b339b2ad-30d5-42be-ae9b-cc6254fe9058"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""966420cf-5e3e-4b92-b5d0-626a9f0dc314"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""47e55e95-244b-4c3c-ab48-a2fc55b08b85"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""df56d66d-1bab-4750-8787-5b6fef8bec45"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""32f2d0a3-5a25-40a9-875d-c345ee781100"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""988ad5bf-2aa8-449e-a133-b98f02ec57b2"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd1f2cc6-203d-412a-a1cd-5ae1412d3e8c"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter Train"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a9b8bea-5df7-4559-99fd-753e9ce35c53"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter Train"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbb2fb10-5f87-45df-b7b1-c353c3d31a00"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rebind Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fe76bf6-f2ba-4733-a2cb-508483da9463"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rebind Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c8c9a4a-2338-44fc-af47-f10bff84811a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa982b6c-c86f-4b02-858b-7366358e7336"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI (Deprecated)"",
            ""id"": ""8ffd9810-9682-4f16-a0f0-0a8c86c5d16f"",
            ""actions"": [
                {
                    ""name"": ""Menu Up"",
                    ""type"": ""Button"",
                    ""id"": ""b61cbf3f-b2b7-4506-acc9-46850b7e2c8c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu Down"",
                    ""type"": ""Button"",
                    ""id"": ""f7b07bc1-ebc5-4e13-8289-c83bfe17e8c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu Left"",
                    ""type"": ""Button"",
                    ""id"": ""a35521b7-15d8-49f4-b741-4467347f1654"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu Right"",
                    ""type"": ""Button"",
                    ""id"": ""5e3fec04-9222-47b6-8d2f-19e2ebe2ca7b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""9f1c625d-1536-4d18-944a-a88012919040"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""88dbd20f-69e8-40e1-be5f-ca979de13b37"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6faaac0b-17c7-4a89-902e-4b170f620f9b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bf522e9-9a14-470e-ac86-a49ed056b3bf"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92304551-870c-4609-87b8-851e53f0337a"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125,max=0.925)"",
                    ""groups"": """",
                    ""action"": ""Menu Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ada08735-84f4-4df1-8d45-55bee562e1e6"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90a8da24-8518-4f12-ad7f-0405abbb8665"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87f2559c-a76e-471e-86bd-4c583800792b"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f9017e3-a652-4dc0-bedc-02f501aedd95"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125,max=0.925)"",
                    ""groups"": """",
                    ""action"": ""Menu Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0dca23d-9dca-4f84-9ec3-1d6712be90df"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""384e12dd-cf8e-4524-8943-2a2e06f1dd32"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d099dc23-25cf-4534-a434-96ac1ec109e5"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ab20b82-3c1c-485c-be07-b43b0b27be42"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125,max=0.925)"",
                    ""groups"": """",
                    ""action"": ""Menu Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""886b2678-aec1-44c3-8ee1-93f05526aa9d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c7053b6-0ee0-4846-a8ce-3f49839c1d59"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dee60699-52c6-48da-a748-6c2bb126fb53"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""079e5347-2050-4a85-ad58-a2000db67e7b"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10d4b052-be4a-4961-b7ef-a15b40a70398"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125,max=0.925)"",
                    ""groups"": """",
                    ""action"": ""Menu Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca81579f-6521-4a1e-a910-6183425dc820"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ee11f12-68bd-4e4d-9819-2070e65bd203"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c81df3c-19d3-4ee7-9019-d64ef9303fe5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d3b3bd0-3cf4-4d03-a443-d1584cb1fb84"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""941569fb-0d9d-48c3-8db1-a84717210151"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""afe36b12-edd3-45e4-8023-23d5deed29f9"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Train
        m_Train = asset.FindActionMap("Train", throwIfNotFound: true);
        m_Train_PressureAbsolute = m_Train.FindAction("Pressure Absolute", throwIfNotFound: true);
        m_Train_PressureModifier = m_Train.FindAction("Pressure Modifier", throwIfNotFound: true);
        m_Train_AccelerationAbsolute = m_Train.FindAction("Acceleration Absolute", throwIfNotFound: true);
        m_Train_AccelerationModifier = m_Train.FindAction("Acceleration Modifier", throwIfNotFound: true);
        m_Train_FocusPanel = m_Train.FindAction("Focus Panel", throwIfNotFound: true);
        m_Train_ExitTrain = m_Train.FindAction("Exit Train", throwIfNotFound: true);
        m_Train_RebindMenu = m_Train.FindAction("Rebind Menu", throwIfNotFound: true);
        m_Train_Menu = m_Train.FindAction("Menu", throwIfNotFound: true);
        m_Train_ChangePerspective = m_Train.FindAction("Change Perspective", throwIfNotFound: true);
        m_Train_SaitekLeft = m_Train.FindAction("Saitek Left", throwIfNotFound: true);
        m_Train_SaitekRight = m_Train.FindAction("Saitek Right", throwIfNotFound: true);
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Camera = m_Player.FindAction("Camera", throwIfNotFound: true);
        m_Player_EnterTrain = m_Player.FindAction("Enter Train", throwIfNotFound: true);
        m_Player_RebindMenu = m_Player.FindAction("Rebind Menu", throwIfNotFound: true);
        m_Player_Menu = m_Player.FindAction("Menu", throwIfNotFound: true);
        // UI (Deprecated)
        m_UIDeprecated = asset.FindActionMap("UI (Deprecated)", throwIfNotFound: true);
        m_UIDeprecated_MenuUp = m_UIDeprecated.FindAction("Menu Up", throwIfNotFound: true);
        m_UIDeprecated_MenuDown = m_UIDeprecated.FindAction("Menu Down", throwIfNotFound: true);
        m_UIDeprecated_MenuLeft = m_UIDeprecated.FindAction("Menu Left", throwIfNotFound: true);
        m_UIDeprecated_MenuRight = m_UIDeprecated.FindAction("Menu Right", throwIfNotFound: true);
        m_UIDeprecated_MenuConfirm = m_UIDeprecated.FindAction("Menu Confirm", throwIfNotFound: true);
        m_UIDeprecated_MenuCancel = m_UIDeprecated.FindAction("Menu Cancel", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Train
    private readonly InputActionMap m_Train;
    private ITrainActions m_TrainActionsCallbackInterface;
    private readonly InputAction m_Train_PressureAbsolute;
    private readonly InputAction m_Train_PressureModifier;
    private readonly InputAction m_Train_AccelerationAbsolute;
    private readonly InputAction m_Train_AccelerationModifier;
    private readonly InputAction m_Train_FocusPanel;
    private readonly InputAction m_Train_ExitTrain;
    private readonly InputAction m_Train_RebindMenu;
    private readonly InputAction m_Train_Menu;
    private readonly InputAction m_Train_ChangePerspective;
    private readonly InputAction m_Train_SaitekLeft;
    private readonly InputAction m_Train_SaitekRight;
    public struct TrainActions
    {
        private @UserInputActions m_Wrapper;
        public TrainActions(@UserInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PressureAbsolute => m_Wrapper.m_Train_PressureAbsolute;
        public InputAction @PressureModifier => m_Wrapper.m_Train_PressureModifier;
        public InputAction @AccelerationAbsolute => m_Wrapper.m_Train_AccelerationAbsolute;
        public InputAction @AccelerationModifier => m_Wrapper.m_Train_AccelerationModifier;
        public InputAction @FocusPanel => m_Wrapper.m_Train_FocusPanel;
        public InputAction @ExitTrain => m_Wrapper.m_Train_ExitTrain;
        public InputAction @RebindMenu => m_Wrapper.m_Train_RebindMenu;
        public InputAction @Menu => m_Wrapper.m_Train_Menu;
        public InputAction @ChangePerspective => m_Wrapper.m_Train_ChangePerspective;
        public InputAction @SaitekLeft => m_Wrapper.m_Train_SaitekLeft;
        public InputAction @SaitekRight => m_Wrapper.m_Train_SaitekRight;
        public InputActionMap Get() { return m_Wrapper.m_Train; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TrainActions set) { return set.Get(); }
        public void SetCallbacks(ITrainActions instance)
        {
            if (m_Wrapper.m_TrainActionsCallbackInterface != null)
            {
                @PressureAbsolute.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnPressureAbsolute;
                @PressureAbsolute.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnPressureAbsolute;
                @PressureAbsolute.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnPressureAbsolute;
                @PressureModifier.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnPressureModifier;
                @PressureModifier.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnPressureModifier;
                @PressureModifier.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnPressureModifier;
                @AccelerationAbsolute.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnAccelerationAbsolute;
                @AccelerationAbsolute.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnAccelerationAbsolute;
                @AccelerationAbsolute.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnAccelerationAbsolute;
                @AccelerationModifier.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnAccelerationModifier;
                @AccelerationModifier.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnAccelerationModifier;
                @AccelerationModifier.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnAccelerationModifier;
                @FocusPanel.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnFocusPanel;
                @FocusPanel.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnFocusPanel;
                @FocusPanel.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnFocusPanel;
                @ExitTrain.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnExitTrain;
                @ExitTrain.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnExitTrain;
                @ExitTrain.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnExitTrain;
                @RebindMenu.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnRebindMenu;
                @RebindMenu.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnRebindMenu;
                @RebindMenu.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnRebindMenu;
                @Menu.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnMenu;
                @ChangePerspective.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnChangePerspective;
                @ChangePerspective.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnChangePerspective;
                @ChangePerspective.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnChangePerspective;
                @SaitekLeft.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnSaitekLeft;
                @SaitekLeft.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnSaitekLeft;
                @SaitekLeft.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnSaitekLeft;
                @SaitekRight.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnSaitekRight;
                @SaitekRight.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnSaitekRight;
                @SaitekRight.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnSaitekRight;
            }
            m_Wrapper.m_TrainActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PressureAbsolute.started += instance.OnPressureAbsolute;
                @PressureAbsolute.performed += instance.OnPressureAbsolute;
                @PressureAbsolute.canceled += instance.OnPressureAbsolute;
                @PressureModifier.started += instance.OnPressureModifier;
                @PressureModifier.performed += instance.OnPressureModifier;
                @PressureModifier.canceled += instance.OnPressureModifier;
                @AccelerationAbsolute.started += instance.OnAccelerationAbsolute;
                @AccelerationAbsolute.performed += instance.OnAccelerationAbsolute;
                @AccelerationAbsolute.canceled += instance.OnAccelerationAbsolute;
                @AccelerationModifier.started += instance.OnAccelerationModifier;
                @AccelerationModifier.performed += instance.OnAccelerationModifier;
                @AccelerationModifier.canceled += instance.OnAccelerationModifier;
                @FocusPanel.started += instance.OnFocusPanel;
                @FocusPanel.performed += instance.OnFocusPanel;
                @FocusPanel.canceled += instance.OnFocusPanel;
                @ExitTrain.started += instance.OnExitTrain;
                @ExitTrain.performed += instance.OnExitTrain;
                @ExitTrain.canceled += instance.OnExitTrain;
                @RebindMenu.started += instance.OnRebindMenu;
                @RebindMenu.performed += instance.OnRebindMenu;
                @RebindMenu.canceled += instance.OnRebindMenu;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @ChangePerspective.started += instance.OnChangePerspective;
                @ChangePerspective.performed += instance.OnChangePerspective;
                @ChangePerspective.canceled += instance.OnChangePerspective;
                @SaitekLeft.started += instance.OnSaitekLeft;
                @SaitekLeft.performed += instance.OnSaitekLeft;
                @SaitekLeft.canceled += instance.OnSaitekLeft;
                @SaitekRight.started += instance.OnSaitekRight;
                @SaitekRight.performed += instance.OnSaitekRight;
                @SaitekRight.canceled += instance.OnSaitekRight;
            }
        }
    }
    public TrainActions @Train => new TrainActions(this);

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Camera;
    private readonly InputAction m_Player_EnterTrain;
    private readonly InputAction m_Player_RebindMenu;
    private readonly InputAction m_Player_Menu;
    public struct PlayerActions
    {
        private @UserInputActions m_Wrapper;
        public PlayerActions(@UserInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Camera => m_Wrapper.m_Player_Camera;
        public InputAction @EnterTrain => m_Wrapper.m_Player_EnterTrain;
        public InputAction @RebindMenu => m_Wrapper.m_Player_RebindMenu;
        public InputAction @Menu => m_Wrapper.m_Player_Menu;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Camera.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCamera;
                @Camera.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCamera;
                @Camera.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCamera;
                @EnterTrain.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEnterTrain;
                @EnterTrain.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEnterTrain;
                @EnterTrain.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEnterTrain;
                @RebindMenu.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRebindMenu;
                @RebindMenu.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRebindMenu;
                @RebindMenu.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRebindMenu;
                @Menu.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMenu;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Camera.started += instance.OnCamera;
                @Camera.performed += instance.OnCamera;
                @Camera.canceled += instance.OnCamera;
                @EnterTrain.started += instance.OnEnterTrain;
                @EnterTrain.performed += instance.OnEnterTrain;
                @EnterTrain.canceled += instance.OnEnterTrain;
                @RebindMenu.started += instance.OnRebindMenu;
                @RebindMenu.performed += instance.OnRebindMenu;
                @RebindMenu.canceled += instance.OnRebindMenu;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI (Deprecated)
    private readonly InputActionMap m_UIDeprecated;
    private IUIDeprecatedActions m_UIDeprecatedActionsCallbackInterface;
    private readonly InputAction m_UIDeprecated_MenuUp;
    private readonly InputAction m_UIDeprecated_MenuDown;
    private readonly InputAction m_UIDeprecated_MenuLeft;
    private readonly InputAction m_UIDeprecated_MenuRight;
    private readonly InputAction m_UIDeprecated_MenuConfirm;
    private readonly InputAction m_UIDeprecated_MenuCancel;
    public struct UIDeprecatedActions
    {
        private @UserInputActions m_Wrapper;
        public UIDeprecatedActions(@UserInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MenuUp => m_Wrapper.m_UIDeprecated_MenuUp;
        public InputAction @MenuDown => m_Wrapper.m_UIDeprecated_MenuDown;
        public InputAction @MenuLeft => m_Wrapper.m_UIDeprecated_MenuLeft;
        public InputAction @MenuRight => m_Wrapper.m_UIDeprecated_MenuRight;
        public InputAction @MenuConfirm => m_Wrapper.m_UIDeprecated_MenuConfirm;
        public InputAction @MenuCancel => m_Wrapper.m_UIDeprecated_MenuCancel;
        public InputActionMap Get() { return m_Wrapper.m_UIDeprecated; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIDeprecatedActions set) { return set.Get(); }
        public void SetCallbacks(IUIDeprecatedActions instance)
        {
            if (m_Wrapper.m_UIDeprecatedActionsCallbackInterface != null)
            {
                @MenuUp.started -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuUp;
                @MenuUp.performed -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuUp;
                @MenuUp.canceled -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuUp;
                @MenuDown.started -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuDown;
                @MenuDown.performed -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuDown;
                @MenuDown.canceled -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuDown;
                @MenuLeft.started -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuLeft;
                @MenuLeft.performed -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuLeft;
                @MenuLeft.canceled -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuLeft;
                @MenuRight.started -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuRight;
                @MenuRight.performed -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuRight;
                @MenuRight.canceled -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuRight;
                @MenuConfirm.started -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuConfirm;
                @MenuConfirm.performed -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuConfirm;
                @MenuConfirm.canceled -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuConfirm;
                @MenuCancel.started -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuCancel;
                @MenuCancel.performed -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuCancel;
                @MenuCancel.canceled -= m_Wrapper.m_UIDeprecatedActionsCallbackInterface.OnMenuCancel;
            }
            m_Wrapper.m_UIDeprecatedActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MenuUp.started += instance.OnMenuUp;
                @MenuUp.performed += instance.OnMenuUp;
                @MenuUp.canceled += instance.OnMenuUp;
                @MenuDown.started += instance.OnMenuDown;
                @MenuDown.performed += instance.OnMenuDown;
                @MenuDown.canceled += instance.OnMenuDown;
                @MenuLeft.started += instance.OnMenuLeft;
                @MenuLeft.performed += instance.OnMenuLeft;
                @MenuLeft.canceled += instance.OnMenuLeft;
                @MenuRight.started += instance.OnMenuRight;
                @MenuRight.performed += instance.OnMenuRight;
                @MenuRight.canceled += instance.OnMenuRight;
                @MenuConfirm.started += instance.OnMenuConfirm;
                @MenuConfirm.performed += instance.OnMenuConfirm;
                @MenuConfirm.canceled += instance.OnMenuConfirm;
                @MenuCancel.started += instance.OnMenuCancel;
                @MenuCancel.performed += instance.OnMenuCancel;
                @MenuCancel.canceled += instance.OnMenuCancel;
            }
        }
    }
    public UIDeprecatedActions @UIDeprecated => new UIDeprecatedActions(this);
    public interface ITrainActions
    {
        void OnPressureAbsolute(InputAction.CallbackContext context);
        void OnPressureModifier(InputAction.CallbackContext context);
        void OnAccelerationAbsolute(InputAction.CallbackContext context);
        void OnAccelerationModifier(InputAction.CallbackContext context);
        void OnFocusPanel(InputAction.CallbackContext context);
        void OnExitTrain(InputAction.CallbackContext context);
        void OnRebindMenu(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnChangePerspective(InputAction.CallbackContext context);
        void OnSaitekLeft(InputAction.CallbackContext context);
        void OnSaitekRight(InputAction.CallbackContext context);
    }
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
        void OnEnterTrain(InputAction.CallbackContext context);
        void OnRebindMenu(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
    }
    public interface IUIDeprecatedActions
    {
        void OnMenuUp(InputAction.CallbackContext context);
        void OnMenuDown(InputAction.CallbackContext context);
        void OnMenuLeft(InputAction.CallbackContext context);
        void OnMenuRight(InputAction.CallbackContext context);
        void OnMenuConfirm(InputAction.CallbackContext context);
        void OnMenuCancel(InputAction.CallbackContext context);
    }
}
