//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Input/UserInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UserInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UserInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UserInputActions"",
    ""maps"": [
        {
            ""name"": ""Train"",
            ""id"": ""c3401460-d25e-4945-9b25-c5ab1063a864"",
            ""actions"": [
                {
                    ""name"": ""Pressure Absolute"",
                    ""type"": ""Value"",
                    ""id"": ""f1e35f4c-0ce3-4673-ad80-9c1ed6bffac4"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""AxisDeadzone(min=1.401298E-45,max=0.975),Invert"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pressure Modifier"",
                    ""type"": ""Value"",
                    ""id"": ""9f92cb2a-f4f3-486b-a49c-e5ed4ac0e959"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""ScaleVector2(x=0),StickDeadzone(min=0.125,max=0.925),Invert"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Acceleration Absolute"",
                    ""type"": ""Value"",
                    ""id"": ""5b6dbf3d-5ad8-42f0-a77d-20dc2a868eff"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""Invert,AxisDeadzone(min=1.401298E-45,max=0.95)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Acceleration Modifier"",
                    ""type"": ""Value"",
                    ""id"": ""cec50a4c-5b71-4f18-83b3-fe85f5c301b8"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""ScaleVector2,StickDeadzone(min=0.125,max=0.925),Invert"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""c5eccd18-05cb-48ca-a4c1-b05f2e639dac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Focus Panel"",
                    ""type"": ""Button"",
                    ""id"": ""ff850ff0-fb46-475a-b4f7-05dae7499649"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rebind Menu"",
                    ""type"": ""Button"",
                    ""id"": ""a766732c-1ccf-416c-ab1c-38fec9f656a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5d536afa-47e0-45ce-baf1-399873dc435b"",
                    ""path"": ""<Gamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0,y=0),StickDeadzone(min=0.125,max=0.95)"",
                    ""groups"": """",
                    ""action"": ""Acceleration Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89b4835a-9b22-4895-8889-82a330183a43"",
                    ""path"": ""<DualShockGamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0,y=0),StickDeadzone(min=0.125,max=0.95)"",
                    ""groups"": """",
                    ""action"": ""Acceleration Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""3c71413e-9a4c-4104-b646-524cde5637e2"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0.5)"",
                    ""groups"": """",
                    ""action"": ""Acceleration Modifier"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7495b12a-8cfe-41f9-a7ca-36c269d2353c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9c342a09-ee82-402f-932b-5c0024be05fb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""dd80d316-717f-47ce-86c3-0e3b4546aed2"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c134669-d072-496b-bf41-20bd1ee864a5"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39497b13-f942-410f-b46b-3a614be55f63"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Focus Panel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50a661b9-8ce0-4461-aff0-568ba5422c7d"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Focus Panel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc1d5b3c-0bb3-4a89-a8f8-8efc811eeed2"",
                    ""path"": ""<Gamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.125,max=0.95)"",
                    ""groups"": """",
                    ""action"": ""Pressure Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1656b6f-d5cc-4233-9812-8fdf92a08a92"",
                    ""path"": ""<DualShockGamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.125,max=0.95)"",
                    ""groups"": """",
                    ""action"": ""Pressure Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""c2c5c978-aa7d-4bd8-842f-ebe657d17151"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0.5)"",
                    ""groups"": """",
                    ""action"": ""Pressure Modifier"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""920a1a07-a841-4f88-8b64-76c960c86066"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pressure Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0b6e660d-6fda-4749-bcf0-5642ed960ad8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pressure Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""668afab4-2866-484d-96e8-cadf4de41b19"",
                    ""path"": ""<HID::Mega World USB Game Controllers>/rz"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration Absolute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45c1ce24-6715-418c-87b3-0e3c29a42350"",
                    ""path"": ""<HID::Mega World USB Game Controllers>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pressure Absolute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72fc7866-1f0a-4ff9-bd93-a5a20edefc44"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rebind Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5cb14a0-6b86-49bc-b1cb-5e1e4fb34962"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rebind Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""8ffd9810-9682-4f16-a0f0-0a8c86c5d16f"",
            ""actions"": [
                {
                    ""name"": ""Menu Up"",
                    ""type"": ""Button"",
                    ""id"": ""b61cbf3f-b2b7-4506-acc9-46850b7e2c8c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu Down"",
                    ""type"": ""Button"",
                    ""id"": ""f7b07bc1-ebc5-4e13-8289-c83bfe17e8c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu Left"",
                    ""type"": ""Button"",
                    ""id"": ""a35521b7-15d8-49f4-b741-4467347f1654"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu Right"",
                    ""type"": ""Button"",
                    ""id"": ""5e3fec04-9222-47b6-8d2f-19e2ebe2ca7b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""9f1c625d-1536-4d18-944a-a88012919040"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""88dbd20f-69e8-40e1-be5f-ca979de13b37"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6faaac0b-17c7-4a89-902e-4b170f620f9b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bf522e9-9a14-470e-ac86-a49ed056b3bf"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92304551-870c-4609-87b8-851e53f0337a"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125,max=0.925)"",
                    ""groups"": """",
                    ""action"": ""Menu Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ada08735-84f4-4df1-8d45-55bee562e1e6"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90a8da24-8518-4f12-ad7f-0405abbb8665"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87f2559c-a76e-471e-86bd-4c583800792b"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f9017e3-a652-4dc0-bedc-02f501aedd95"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125,max=0.925)"",
                    ""groups"": """",
                    ""action"": ""Menu Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0dca23d-9dca-4f84-9ec3-1d6712be90df"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""384e12dd-cf8e-4524-8943-2a2e06f1dd32"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d099dc23-25cf-4534-a434-96ac1ec109e5"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ab20b82-3c1c-485c-be07-b43b0b27be42"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125,max=0.925)"",
                    ""groups"": """",
                    ""action"": ""Menu Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""886b2678-aec1-44c3-8ee1-93f05526aa9d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c7053b6-0ee0-4846-a8ce-3f49839c1d59"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dee60699-52c6-48da-a748-6c2bb126fb53"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""079e5347-2050-4a85-ad58-a2000db67e7b"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10d4b052-be4a-4961-b7ef-a15b40a70398"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125,max=0.925)"",
                    ""groups"": """",
                    ""action"": ""Menu Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca81579f-6521-4a1e-a910-6183425dc820"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ee11f12-68bd-4e4d-9819-2070e65bd203"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c81df3c-19d3-4ee7-9019-d64ef9303fe5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d3b3bd0-3cf4-4d03-a443-d1584cb1fb84"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""941569fb-0d9d-48c3-8db1-a84717210151"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""afe36b12-edd3-45e4-8023-23d5deed29f9"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerAvatar"",
            ""id"": ""a9e6506c-c1bf-4d85-8a8f-22ba5905ce03"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""eb44c0d4-c50b-4b43-9905-c73d6ebd4b65"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Camera"",
                    ""type"": ""Value"",
                    ""id"": ""3aaa53cd-9b20-4b81-bc04-100b49279eeb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1485c671-220e-4490-85dd-03612a1bc036"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d8a84d37-1e87-43af-bdb1-069d7ab98728"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b339b2ad-30d5-42be-ae9b-cc6254fe9058"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""966420cf-5e3e-4b92-b5d0-626a9f0dc314"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""47e55e95-244b-4c3c-ab48-a2fc55b08b85"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""df56d66d-1bab-4750-8787-5b6fef8bec45"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""32f2d0a3-5a25-40a9-875d-c345ee781100"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""988ad5bf-2aa8-449e-a133-b98f02ec57b2"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Train
        m_Train = asset.FindActionMap("Train", throwIfNotFound: true);
        m_Train_PressureAbsolute = m_Train.FindAction("Pressure Absolute", throwIfNotFound: true);
        m_Train_PressureModifier = m_Train.FindAction("Pressure Modifier", throwIfNotFound: true);
        m_Train_AccelerationAbsolute = m_Train.FindAction("Acceleration Absolute", throwIfNotFound: true);
        m_Train_AccelerationModifier = m_Train.FindAction("Acceleration Modifier", throwIfNotFound: true);
        m_Train_Menu = m_Train.FindAction("Menu", throwIfNotFound: true);
        m_Train_FocusPanel = m_Train.FindAction("Focus Panel", throwIfNotFound: true);
        m_Train_RebindMenu = m_Train.FindAction("Rebind Menu", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_MenuUp = m_UI.FindAction("Menu Up", throwIfNotFound: true);
        m_UI_MenuDown = m_UI.FindAction("Menu Down", throwIfNotFound: true);
        m_UI_MenuLeft = m_UI.FindAction("Menu Left", throwIfNotFound: true);
        m_UI_MenuRight = m_UI.FindAction("Menu Right", throwIfNotFound: true);
        m_UI_MenuConfirm = m_UI.FindAction("Menu Confirm", throwIfNotFound: true);
        m_UI_MenuCancel = m_UI.FindAction("Menu Cancel", throwIfNotFound: true);
        // PlayerAvatar
        m_PlayerAvatar = asset.FindActionMap("PlayerAvatar", throwIfNotFound: true);
        m_PlayerAvatar_Movement = m_PlayerAvatar.FindAction("Movement", throwIfNotFound: true);
        m_PlayerAvatar_Camera = m_PlayerAvatar.FindAction("Camera", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Train
    private readonly InputActionMap m_Train;
    private ITrainActions m_TrainActionsCallbackInterface;
    private readonly InputAction m_Train_PressureAbsolute;
    private readonly InputAction m_Train_PressureModifier;
    private readonly InputAction m_Train_AccelerationAbsolute;
    private readonly InputAction m_Train_AccelerationModifier;
    private readonly InputAction m_Train_Menu;
    private readonly InputAction m_Train_FocusPanel;
    private readonly InputAction m_Train_RebindMenu;
    public struct TrainActions
    {
        private @UserInputActions m_Wrapper;
        public TrainActions(@UserInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PressureAbsolute => m_Wrapper.m_Train_PressureAbsolute;
        public InputAction @PressureModifier => m_Wrapper.m_Train_PressureModifier;
        public InputAction @AccelerationAbsolute => m_Wrapper.m_Train_AccelerationAbsolute;
        public InputAction @AccelerationModifier => m_Wrapper.m_Train_AccelerationModifier;
        public InputAction @Menu => m_Wrapper.m_Train_Menu;
        public InputAction @FocusPanel => m_Wrapper.m_Train_FocusPanel;
        public InputAction @RebindMenu => m_Wrapper.m_Train_RebindMenu;
        public InputActionMap Get() { return m_Wrapper.m_Train; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TrainActions set) { return set.Get(); }
        public void SetCallbacks(ITrainActions instance)
        {
            if (m_Wrapper.m_TrainActionsCallbackInterface != null)
            {
                @PressureAbsolute.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnPressureAbsolute;
                @PressureAbsolute.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnPressureAbsolute;
                @PressureAbsolute.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnPressureAbsolute;
                @PressureModifier.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnPressureModifier;
                @PressureModifier.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnPressureModifier;
                @PressureModifier.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnPressureModifier;
                @AccelerationAbsolute.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnAccelerationAbsolute;
                @AccelerationAbsolute.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnAccelerationAbsolute;
                @AccelerationAbsolute.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnAccelerationAbsolute;
                @AccelerationModifier.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnAccelerationModifier;
                @AccelerationModifier.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnAccelerationModifier;
                @AccelerationModifier.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnAccelerationModifier;
                @Menu.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnMenu;
                @FocusPanel.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnFocusPanel;
                @FocusPanel.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnFocusPanel;
                @FocusPanel.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnFocusPanel;
                @RebindMenu.started -= m_Wrapper.m_TrainActionsCallbackInterface.OnRebindMenu;
                @RebindMenu.performed -= m_Wrapper.m_TrainActionsCallbackInterface.OnRebindMenu;
                @RebindMenu.canceled -= m_Wrapper.m_TrainActionsCallbackInterface.OnRebindMenu;
            }
            m_Wrapper.m_TrainActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PressureAbsolute.started += instance.OnPressureAbsolute;
                @PressureAbsolute.performed += instance.OnPressureAbsolute;
                @PressureAbsolute.canceled += instance.OnPressureAbsolute;
                @PressureModifier.started += instance.OnPressureModifier;
                @PressureModifier.performed += instance.OnPressureModifier;
                @PressureModifier.canceled += instance.OnPressureModifier;
                @AccelerationAbsolute.started += instance.OnAccelerationAbsolute;
                @AccelerationAbsolute.performed += instance.OnAccelerationAbsolute;
                @AccelerationAbsolute.canceled += instance.OnAccelerationAbsolute;
                @AccelerationModifier.started += instance.OnAccelerationModifier;
                @AccelerationModifier.performed += instance.OnAccelerationModifier;
                @AccelerationModifier.canceled += instance.OnAccelerationModifier;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @FocusPanel.started += instance.OnFocusPanel;
                @FocusPanel.performed += instance.OnFocusPanel;
                @FocusPanel.canceled += instance.OnFocusPanel;
                @RebindMenu.started += instance.OnRebindMenu;
                @RebindMenu.performed += instance.OnRebindMenu;
                @RebindMenu.canceled += instance.OnRebindMenu;
            }
        }
    }
    public TrainActions @Train => new TrainActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_MenuUp;
    private readonly InputAction m_UI_MenuDown;
    private readonly InputAction m_UI_MenuLeft;
    private readonly InputAction m_UI_MenuRight;
    private readonly InputAction m_UI_MenuConfirm;
    private readonly InputAction m_UI_MenuCancel;
    public struct UIActions
    {
        private @UserInputActions m_Wrapper;
        public UIActions(@UserInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MenuUp => m_Wrapper.m_UI_MenuUp;
        public InputAction @MenuDown => m_Wrapper.m_UI_MenuDown;
        public InputAction @MenuLeft => m_Wrapper.m_UI_MenuLeft;
        public InputAction @MenuRight => m_Wrapper.m_UI_MenuRight;
        public InputAction @MenuConfirm => m_Wrapper.m_UI_MenuConfirm;
        public InputAction @MenuCancel => m_Wrapper.m_UI_MenuCancel;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @MenuUp.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuUp;
                @MenuUp.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuUp;
                @MenuUp.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuUp;
                @MenuDown.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuDown;
                @MenuDown.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuDown;
                @MenuDown.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuDown;
                @MenuLeft.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuLeft;
                @MenuLeft.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuLeft;
                @MenuLeft.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuLeft;
                @MenuRight.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuRight;
                @MenuRight.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuRight;
                @MenuRight.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuRight;
                @MenuConfirm.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuConfirm;
                @MenuConfirm.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuConfirm;
                @MenuConfirm.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuConfirm;
                @MenuCancel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuCancel;
                @MenuCancel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuCancel;
                @MenuCancel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuCancel;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MenuUp.started += instance.OnMenuUp;
                @MenuUp.performed += instance.OnMenuUp;
                @MenuUp.canceled += instance.OnMenuUp;
                @MenuDown.started += instance.OnMenuDown;
                @MenuDown.performed += instance.OnMenuDown;
                @MenuDown.canceled += instance.OnMenuDown;
                @MenuLeft.started += instance.OnMenuLeft;
                @MenuLeft.performed += instance.OnMenuLeft;
                @MenuLeft.canceled += instance.OnMenuLeft;
                @MenuRight.started += instance.OnMenuRight;
                @MenuRight.performed += instance.OnMenuRight;
                @MenuRight.canceled += instance.OnMenuRight;
                @MenuConfirm.started += instance.OnMenuConfirm;
                @MenuConfirm.performed += instance.OnMenuConfirm;
                @MenuConfirm.canceled += instance.OnMenuConfirm;
                @MenuCancel.started += instance.OnMenuCancel;
                @MenuCancel.performed += instance.OnMenuCancel;
                @MenuCancel.canceled += instance.OnMenuCancel;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // PlayerAvatar
    private readonly InputActionMap m_PlayerAvatar;
    private IPlayerAvatarActions m_PlayerAvatarActionsCallbackInterface;
    private readonly InputAction m_PlayerAvatar_Movement;
    private readonly InputAction m_PlayerAvatar_Camera;
    public struct PlayerAvatarActions
    {
        private @UserInputActions m_Wrapper;
        public PlayerAvatarActions(@UserInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerAvatar_Movement;
        public InputAction @Camera => m_Wrapper.m_PlayerAvatar_Camera;
        public InputActionMap Get() { return m_Wrapper.m_PlayerAvatar; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerAvatarActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerAvatarActions instance)
        {
            if (m_Wrapper.m_PlayerAvatarActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerAvatarActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerAvatarActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerAvatarActionsCallbackInterface.OnMovement;
                @Camera.started -= m_Wrapper.m_PlayerAvatarActionsCallbackInterface.OnCamera;
                @Camera.performed -= m_Wrapper.m_PlayerAvatarActionsCallbackInterface.OnCamera;
                @Camera.canceled -= m_Wrapper.m_PlayerAvatarActionsCallbackInterface.OnCamera;
            }
            m_Wrapper.m_PlayerAvatarActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Camera.started += instance.OnCamera;
                @Camera.performed += instance.OnCamera;
                @Camera.canceled += instance.OnCamera;
            }
        }
    }
    public PlayerAvatarActions @PlayerAvatar => new PlayerAvatarActions(this);
    public interface ITrainActions
    {
        void OnPressureAbsolute(InputAction.CallbackContext context);
        void OnPressureModifier(InputAction.CallbackContext context);
        void OnAccelerationAbsolute(InputAction.CallbackContext context);
        void OnAccelerationModifier(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnFocusPanel(InputAction.CallbackContext context);
        void OnRebindMenu(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnMenuUp(InputAction.CallbackContext context);
        void OnMenuDown(InputAction.CallbackContext context);
        void OnMenuLeft(InputAction.CallbackContext context);
        void OnMenuRight(InputAction.CallbackContext context);
        void OnMenuConfirm(InputAction.CallbackContext context);
        void OnMenuCancel(InputAction.CallbackContext context);
    }
    public interface IPlayerAvatarActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
    }
}
